### Create a new user
POST http://localhost:3000/auth/signup 
content-type: application/json

{
  "email": "asdf1@asdf.com",
  "password": "asdl"
}

### login a user
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "asdf2@asdf.com",
  "password": "asdl"
}

###get cur user
GET http://localhost:3000/auth/whoami

### logout a user
POST http://localhost:3000/auth/signout

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@asdf.com

### Delete a user given id
DELETE http://localhost:3000/auth/6

### Update a user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "password": "aba"
}

